# Copyright (c) 2021 Nordic Semiconductor ASA
# SPDX-License-Identifier: Apache-2.0

manifest:
  self:
    west-commands: scripts/west-commands.yml

  remotes:
    - name: ncs
      url-base: https://github.com/nrfconnect
    - name: ncs-docker
      url-base: https://github.com/NordicPlayground


  projects:
    - name: nrf
      remote: ncs
      repo-path: sdk-nrf
      revision: v2.6.0
      import: true
    - name: ncs-docker
      remote: ncs-docker
      revision: saga
      repo-path: nrf-docker

